### ISSUE TITLE
status of 422 (Unprocessable Entity) on 'PUT /run/{runid}/step/{stepid}'

### ISSUE THREAD

**Issue by johmats** [mescobrad-project/ExpertSystem#30]
Trying to have a PUT on the endpoint  '/run/' + run_id + '/step/' + stepid but the server responded with 
'a status of 422 (Unprocessable Entity)'
Could you please provide me with the body of that call?

Thanks in advance.

**Comment by johmats** [comment]
![run:runid:step:stepid](https://user-images.githubusercontent.com/45197752/185798300-e94c9e6f-cb73-447e-9bac-5f46dc027dea.png)

**Comment by doskelfsy** [comment]
See PR #34 
Updated Docs @ [d8f273c](https://github.com/mescobrad-project/ExpertSystem/pull/34/commits/d8f273c0b2b0ea46cae830112ceccd0a7695b3be)
