### ISSUE TITLE
provide list of the Process types available and mapping of them

### ISSUE THREAD

**Issue by johmats** [mescobrad-project/ExpertSystem#32]
Please provide the mapping of the available process types that can be saved as Tasks.
eg. startEvent, ParallelGateway, exclusiveGateaway

**Comment by doskelfsy** [comment]
#33 [9a8cc3d](https://github.com/mescobrad-project/ExpertSystem/pull/33/commits/9a8cc3d2a04c408b7f0b2c9ad59da1d56ccc1508)
